# Training parameters
training:
  num_epochs: 25
  batch_size: 64
  learning_rate: 0.000025
  scheduler_patience: 3
  scheduler_factor: 0.1

# Data parameters
data:
  dataset: "cifar10"
  data_dir: '../datasets/cifar10'
  train_dir: '../datasets/cats_and_dogs/train'
  val_dir: '../datasets/cats_and_dogs/val'
  test_dir: '../datasets/cats_and_dogs/test'
  num_workers: 4

# Model parameters
model:
  name: 'alexnet'
  is_pretrained: true 
  num_classes: 10 # This will be overridden based on dataset

# Experiment tracking
experiment:
  label: 'alexnet_pretrained_cifar10'
  output_dir: './experiments'
  save_model: true

random_seed: 24