# Training parameters
training:
  num_epochs: 35
  batch_size: 64
  learning_rate: 0.00025
  scheduler_patience: 3
  scheduler_factor: 0.1

# Data parameters
data:
  dataset: "cats_dogs"
  data_dir: '../datasets/cifar10'
  train_dir: '../datasets/cats_and_dogs/train'
  val_dir: '../datasets/cats_and_dogs/val'
  test_dir: '../datasets/cats_and_dogs/test'
  num_workers: 4

# Model parameters
model:
  name: 'vgg16'
  is_pretrained: false 
  num_classes: 2  # This will be overridden based on dataset

# Experiment tracking
experiment:
  label: 'vgg_pretrained_cats_dogs_1'
  output_dir: './experiments'
  save_model: true