# Training parameters
training:
  num_epochs: 35
  batch_size: 256
  learning_rate: 0.0001
  scheduler_patience: 3
  scheduler_factor: 0.1

# Data parameters
data:
  train_dir: '../datasets/train'
  val_dir: '../datasets/val'
  test_dir: '../datasets/test'
  num_workers: 4

# Model parameters
model:
  num_classes: 2  # This will be overridden based on dataset

# Experiment tracking
experiment:
  output_dir: './experiments'
  save_model: true